---
- hosts: worker
  become: yes
  vars_files:
    - host_vars/worker.yml
  tasks:
  - hostname:
      name: "{{ hostname }}"

  - name: fqdns
    lineinfile:
      path: /etc/hosts
      regexp: '^127\.0\.0\.1\s'
      line: "127.0.0.1 {{ hostname }} localhost"
